"""create user exchange table

Revision ID: 0923bab40121
Revises: 44eefd0db097
Create Date: 2025-12-04 16:23:32.602823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0923bab40121'
down_revision = '44eefd0db097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_secret', sa.String(length=255), nullable=False),
    sa.Column('passphrase', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_exchanges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_exchanges'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exchanges')
    # ### end Alembic commands ###
