"""add the field step in user table

Revision ID: 1375d6a2108b
Revises: a27c71be74a5
Create Date: 2025-11-25 10:25:54.711599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1375d6a2108b'
down_revision = 'a27c71be74a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
