"""add the mfa key

Revision ID: 1c4ebada0ded
Revises: af38c81c6055
Create Date: 2025-11-15 13:36:52.395038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4ebada0ded'
down_revision = 'af38c81c6055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
