"""add the fields in subscription table

Revision ID: 317834876a72
Revises: 94d7c689b660
Create Date: 2025-12-05 11:07:54.153064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317834876a72'
down_revision = '94d7c689b660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('final_cancellation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'final_cancellation_date')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###
