"""add the plan type field in subscription table

Revision ID: 44eefd0db097
Revises: 5affeea04785
Create Date: 2025-11-27 16:52:03.649001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44eefd0db097'
down_revision = '5affeea04785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'plan_type')
    # ### end Alembic commands ###
