"""add the field in user table for stripe customer_id 

Revision ID: 49fe0a41ab32
Revises: a65ab3549ea0
Create Date: 2025-11-25 18:42:19.688992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fe0a41ab32'
down_revision = 'a65ab3549ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
