"""add nullable true in exchange field

Revision ID: 5565a553f0bc
Revises: 317834876a72
Create Date: 2025-12-05 11:16:31.648329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5565a553f0bc'
down_revision = '317834876a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
