"""add deafult vallue in a cancel at priod end field 

Revision ID: 55fbb5933430
Revises: 5565a553f0bc
Create Date: 2025-12-08 13:49:50.090796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fbb5933430'
down_revision = '5565a553f0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
