"""unique phone number

Revision ID: 775b6674f2cb
Revises: 47ef392b3e4f
Create Date: 2025-12-23 17:34:17.896123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775b6674f2cb'
down_revision = '47ef392b3e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_phone_number'), 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_phone_number'), 'users', type_='unique')
    # ### end Alembic commands ###
