"""add the is_exchange_connected key in user table

Revision ID: 94d7c689b660
Revises: 0923bab40121
Create Date: 2025-12-04 16:50:23.276342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d7c689b660'
down_revision = '0923bab40121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exchanges', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_exchange_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_exchange_connected')
    op.drop_column('user_exchanges', 'created_at')
    # ### end Alembic commands ###
