"""add the field step in user table

Revision ID: a27c71be74a5
Revises: f0f74dc4104d
Create Date: 2025-11-25 10:23:30.646332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27c71be74a5'
down_revision = 'f0f74dc4104d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
