"""add the field bool field of address and payment

Revision ID: a65ab3549ea0
Revises: ae215320e9fc
Create Date: 2025-11-25 11:13:17.525758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65ab3549ea0'
down_revision = 'ae215320e9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_address_filled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_payment_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_payment_done')
    op.drop_column('users', 'is_address_filled')
    # ### end Alembic commands ###
