"""Add the email otp expire

Revision ID: aad120cc7344
Revises: c4e6b85ef60d
Create Date: 2025-11-15 11:02:45.082777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad120cc7344'
down_revision = 'c4e6b85ef60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
