"""add the field step in user table

Revision ID: ae215320e9fc
Revises: 1375d6a2108b
Create Date: 2025-11-25 10:25:59.402799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae215320e9fc'
down_revision = '1375d6a2108b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
