"""add the mfa key

Revision ID: af38c81c6055
Revises: daf90dad3260
Create Date: 2025-11-15 13:35:38.394859

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af38c81c6055"
down_revision = "daf90dad3260"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
