"""Add full_name column

Revision ID: c4e6b85ef60d
Revises: 3215d72f05a0
Create Date: 2025-11-15 10:07:33.000080

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4e6b85ef60d"
down_revision = "3215d72f05a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "users", sa.Column("country_code", sa.String(length=10), nullable=True)
    )
    op.add_column("users", sa.Column("email_otp", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("phone_otp", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("is_email_verify", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_mfa", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_phone_verify", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(length=50), nullable=True))
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "role")
    op.drop_column("users", "is_phone_verify")
    op.drop_column("users", "is_mfa")
    op.drop_column("users", "is_email_verify")
    op.drop_column("users", "phone_otp")
    op.drop_column("users", "email_otp")
    op.drop_column("users", "country_code")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
