"""add the mfa key

Revision ID: daf90dad3260
Revises: 798fac5bf9fa
Create Date: 2025-11-15 12:29:28.638947

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "daf90dad3260"
down_revision = "798fac5bf9fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("mfa_secret", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_mfa_enabled", sa.Boolean(), nullable=True))
    op.drop_column("users", "is_mfa")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_mfa", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "is_mfa_enabled")
    op.drop_column("users", "mfa_secret")
    # ### end Alembic commands ###
