"""add the field step in user table

Revision ID: f0f74dc4104d
Revises: 1c4ebada0ded
Create Date: 2025-11-25 10:21:17.422661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f74dc4104d'
down_revision = '1c4ebada0ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'step')
    # ### end Alembic commands ###
